#!/bin/bash

get_vmname () {
  echo $1 | awk 'BEGIN { FS = "-" } ; {print $1"-"$2}'
}

vmname=$(get_vmname $1)

exec qemu-system-x86_64 -enable-kvm \
  -cpu host \
  -drive file=$vmname.cow,if=virtio \
  -drive if=pflash,format=raw,file=$vmname.fd \
  -netdev user,id=vmnic,hostname=$vmname \
  -device virtio-net,netdev=vmnic \
  -device virtio-rng-pci \
  -m 2048M \
  -smp 2 \
  -monitor stdio \
  -name $vmname \
  -boot d \
  -cdrom $1
